import {Roboto} from 'next/font/google'
import Provider from "@/providers/Provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import '../style/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({subsets:['latin'],weight:['300','400','500','700']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <Provider>        
            <main className="flex w-full min-h-[50vh] justify-center bg-[#F7F5F2]">
              {children}
            </main>
        </Provider>
        <Footer />
      </body>
    </html>
  )
}
